services:
  - type: web
    name: kfats-server
    env: node
    region: singapore
    plan: free
    buildCommand: |
      npm ci
      npm run build
    startCommand: npm start
    nodeVersion: 18
    envVars:
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_PRODUCTION
        value: "false" 